# skeleton code generated by chatgpt

import cv2
import matplotlib.pyplot as plt
import numpy as np

def main():
    # Load the image and convert it to grayscale
    img = cv2.imread('example.jpg', cv2.IMREAD_GRAYSCALE)

    # Display the image using Matplotlib
    plt.imshow(img, cmap='gray')
    plt.show()


if __name__ == "__main__":
    main()

